
mode: ['MP']
dataset_type: ['Students', 'PD'] #'PD', 'Healthy',

image_save: True

PD:
  path_to_directory: 'C:/Users/maksi/Desktop/Грант_НЦН/PD_data/PD/'
  number: [93]
#  number: [ 2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
#       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
#       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
#       54, 56, 57,  61, 62, 63, 64, 66, 67, 68, 70, 71, 72, 75, 81, 83, 90, 91]
  folder_name: 'Patient'

Healthy:
  path_to_directory: 'C:/Users/maksi/BMSTU/PD/Patient_mp'
  number: []
  folder_name: 'Healthy'

Students:
  path_to_directory: "C:/Users/maksi/Desktop/Грант_НЦН/PD_data/STUDENTS"
  number: []
  folder_name: 'student'

hand:
  input_folder: 'handv22'
  output_folder: 'auto_algorithm_hand'
  threshold: 20 #TODO
  timestamp: 'frame'
  threshold_data_length: 800
  exercise: ['FT', 'OC', 'PS']
  auto_alg_class:
    _target_: automarking.adaptive.Adaptive

MP:
  input_folder: 'MP'
  output_folder: 'auto_algorithm_MP'
  threshold: 20 #TODO
  mode: 'angle'
  timestamp: 'frame'
  threshold_data_length: 200
  exercise: ['FT', 'OC', 'PS']
  auto_alg_class:
    _target_: automarking.adaptive.Adaptive

face:
  output_folder: 'auto_algorithm_face'
  threshold: 0.1 #TODO
  threshold_data_length: 5
  exercise:
    'p5': [ 'AU12' ]
    'p11': [ 'AU4' ]
  auto_alg_class:
    _target_: automarking.auto_face.AutoFace
