
mode: ['hand', 'face']
dataset_type: ['PD', 'Healthy','Students'] #'PD', 'Healthy',

image_save: False

PD:
  path_to_directory: 'D://PD'
  number: [1, 2,  3,  4,  5,  6,  7,  8,  9,
           11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
           21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
           31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
           41, 42, 43, 44, 45, 46, 47, 49,
           52, 53, 54, 55, 56, 57, 58, 59, 60,
           61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
           71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
           81, 82, 83, 85, 86, 87, 90,
           91, 92, 93, 94, 95, 96, 97]
#  number: [ 2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
#       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
#       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
#       54, 56, 57,  61, 62, 63, 64, 66, 67, 68, 70, 71, 72, 75, 81, 83, 90, 91]
  folder_name: 'Patient'

Healthy:
  path_to_directory: 'D://HEALTHY'
  number: [1, 2, 3, 4, 6, 7, 8, 9, 10 ,11, 12 ,13, 14, 15, 16, 17, 18]
  folder_name: 'Healthy'

Students:
  path_to_directory: 'D://STUDENTS'
  number: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11, 12 ,13, 14, 15]
  folder_name: 'student'

hand:
  output_folder: 'auto_algorithm_hand'
  threshold: 20 #TODO
  threshold_data_length: 800
  exercise: ['FT', 'OC', 'PS']
  auto_alg_class:
    _target_: automarking.adaptive.Adaptive

face:
  output_folder: 'auto_algorithm_face'
  threshold: 0.1 #TODO
  threshold_data_length: 5
  exercise:
    'p5': [ 'AU12' ]
    'p11': [ 'AU4' ]
  auto_alg_class:
    _target_: automarking.auto_face.AutoFace
