class_name:
  _target_: preprocessing.raw_data_processing.PreProcessing

task_name: preprocessing

process_face: False
process_hand_LM: True
process_hand_MP: True

hand_folder_LM: 'handv22'
hand_folder_PM: 'handPM'
face_folder: 'face'

path_to_lmt_exe: 'D:\\Programs\\leapmotionv22\\' #'D:\\Programs\\leapmotion\\'
path_to_openface: 'D:\\Programs\\openface\\Release\\' #'E:\\EXeFiles\\OpenFace-master\\x64\\Release\\'

PD:
  path_to_directory: 'D://PD'
  id_name: 'Patient'
  numbers: [100,102]

HEALTHY:
  path_to_directory: 'D://HEALTHY'
  id_name: 'Healthy'
  numbers: []

STUDENT:
  path_to_directory: 'D://STUDENTS'
  id_name: 'student'
  numbers: []

every_frames: 5
video_sequence: ['p1', 'p2', 'p3', 'p5', 'p11', 'p12_1', 'p12_2', 'p12_3', 'p12_4', 'p12_5', 'p12_6', 'p13_1', 'p13_2', 'p13_3', 'p13_4', 'p13_5', 'p13_6']


