class_name:
  _target_: preprocessing.raw_data_processing.PreProcessing

task_name: preprocessing

process_face: True
process_hand: False

path_to_lmt_exe: 'D:\\Programs\\leapmotion\\'
path_to_openface: 'D:\\Programs\\openface\\Release\\' #'E:\\EXeFiles\\OpenFace-master\\x64\\Release\\'

PD:
  path_to_directory: 'D://PD'
  id_name: 'Patient'
  numbers: []

HEALTHY:
  path_to_directory: 'D://HEALTHY'
  id_name: 'Healthy'
  numbers: []

STUDENT:
  path_to_directory: 'D://STUDENTS'
  id_name: 'student'
  numbers: [16]

every_frames: 5
video_sequence: ['p1', 'p2', 'p3', 'p5', 'p11', 'p12_1', 'p12_2', 'p12_3', 'p12_4', 'p12_5', 'p12_6', 'p13_1', 'p13_2', 'p13_3', 'p13_4', 'p13_5', 'p13_6']


