defaults:
  - _self_
  - hydra: default

class_name:
  _target_: statistic.statistic.Statistic

task_name: statistics

datasets: ['PD', 'HEALTHY', 'STUDENT']
mode: ['hand', 'face', 'em', 'tremor']
stages: [0,1,2,3]
face_data_quality: [1,2,3,4,5]
hand_data_quality: [1,2,3,4,5]

2.5: 3
3.5: 3

#statistic_binary: True
#statistic_stages: True

save_diagram: True
aggregation_type: '50%'

stat_critery: ['t-test', 'mann']
#stat_comparison_binary: True
#stat_comparison_stage: True

meta_statistic: ['gender', 'age', 'stage', 'datasets']

outlayer_analysis: True #TODO

path: 'D:\PDResearch\experiments\feature_extraction\runs\'
folder: '2024-08-24_16-48-54' #'2024-08-18_23-50-53' #'2024-08-18_17-52-58' #'2024-08-17_18-52-03' #'2024-08-16_20-29-50' #'2024-08-16_13-09-56' #'2024-08-11_19-08-33' #'2024-08-11_01-06-51' #'2024-08-05_17-51-15' #'2024-07-29_23-34-45' #'2024-07-28_23-27-26'
hand:
  file: 'hand_feature.csv'
  feature_type: [ 'NumA', 'AvgFrq', 'AvgVopen', 'AvgVclose', 'AvgA', 'VarA', 'VarVopen','VarFrq', 'DecA','DecV', 'NumADiff', 'AvgFrqDiff', 'AvgVopenDiff', 'AvgVcloseDiff', 'AvgADiff', 'VarADiff', 'VarVopenDiff','VarFrqDiff', 'DecADiff','DecVDiff' ]
  exercise: [ 'FT', 'OC', 'PS' ]
  datasets: ['PD', 'HEALTHY']

face:
  file: 'face_feature.csv'
  feature_type: [ 'NumAF', 'AvgFrqF','AvgVopen','AvgVclose','AvgA','VarA','VarVopen','VarVclose','VarFrqF','DecFA','DecFV','Length']
  exercise: ['AU12_p5', 'AU4_p11']
  datasets: ['PD', 'HEALTHY']

em:
  file: 'em_feature.csv'
  feature_type: [ 'Anger', 'Disgust', 'Fear','Happiness','Sadness','Surprise' ]
  exercise: ['DA', 'DI' ] #'DA',
  datasets: ['PD', 'HEALTHY']

tremor:
  file: 'tremor_feature.csv'
  feature_type: ['Fmean', 'Amean', 'Fmax', 'Amax']
  exercise: ['FORE_TIP']
  datasets: ['PD', 'STUDENT']



