defaults:
  - _self_
  - hydra: default

class_name:
  _target_: statistic.statistic.Statistic

task_name: statistics

datasets: ['PD', 'HEALTHY', 'STUDENT']
mode: ['tremor'] #['hand', 'face', 'em', 'tremor', 'blinking']
stages: [0,1,2,3]
face_data_quality: [1,2,3,4,5]
hand_data_quality: [1,2,3,4,5]

2.5: 3
3.5: 3

#statistic_binary: True
#statistic_stages: True

save_diagram: True
aggregation_type: 'mean' #'50%'

stat_critery: ['t-test', 'mann']
#stat_comparison_binary: True
#stat_comparison_stage: True

meta_statistic: ['gender', 'age', 'stage', 'datasets']

outlayer_analysis: True #TODO

path: 'D:\PDResearch\experiments\feature_extraction\runs\'
folder: '2025-05-08_01-42-24' #'2025-05-08_15-33-10' #'2025-04-30_15-16-43' article #'2025-04-30_14-32-47' #'2025-04-29_19-31-52' #'2025-04-01_18-35-35' #'2025-04-18_01-22-33' #'2025-04-01_18-35-35' #'2025-03-25_18-18-50' #'2025-03-14_18-30-48' #'2024-11-07_01-04-45' #'2024-10-21_18-49-30' #'2024-09-20_13-53-10' #'2024-08-24_16-48-54' #'2024-08-18_23-50-53' #'2024-08-18_17-52-58' #'2024-08-17_18-52-03' #'2024-08-16_20-29-50' #'2024-08-16_13-09-56' #'2024-08-11_19-08-33' #'2024-08-11_01-06-51' #'2024-08-05_17-51-15' #'2024-07-29_23-34-45' #'2024-07-28_23-27-26'
hand:
  file: 'hand_feature.csv'
  #feature_type: [ 'NumA', 'AvgFrq', 'AvgVopen', 'AvgVclose', 'AvgA', 'VarA', 'VarVopen','VarFrq', 'DecA','DecV', 'NumADiff', 'AvgFrqDiff', 'AvgVopenDiff', 'AvgVcloseDiff', 'AvgADiff', 'VarADiff', 'VarVopenDiff','VarFrqDiff', 'DecADiff','DecVDiff' ]
  #feature_type: [ 'NumA', 'AvgFrq', 'AvgVopen', 'AvgA', 'VarA', 'VarVopen','VarFrq', 'DecA','DecV','DecLin','NumADiff', 'AvgFrqDiff', 'AvgVopenDiff', 'AvgADiff', 'VarADiff', 'VarVopenDiff','VarFrqDiff', 'DecADiff','DecVDiff','DecLinDiff' ]
  feature_type: [ 'NumA', 'AvgFrq', 'AvgVopen', 'AvgA', 'VarA', 'VarVopen','VarFrq', 'DecA','DecV','DecLin',]
  #feature_type: ['NumADiff', 'AvgFrqDiff', 'AvgVopenDiff', 'AvgVcloseDiff', 'AvgADiff', 'VarADiff', 'VarVopenDiff','VarFrqDiff', 'DecADiff','DecVDiff' ]
  exercise: [ 'FT', 'OC', 'PS' ]
  datasets: ['PD', 'HEALTHY']
  MDS-UPDRS:
    FT: ['3.4_FT']
    OC: ['3.5_OC']
    PS: ['3.6_PS']

face:
  file: 'face_feature.csv'
  #feature_type: [ 'NumAF', 'AvgFrqF','AvgVopen','AvgVclose','AvgA','VarA','VarVopen','VarVclose','VarFrqF','DecFA','DecFV','Length']
  feature_type: ['AvgFrqF','AvgVopen','AvgA','VarA','VarVopen','VarFrqF','DecFA','DecFV','Length','DecLin']
  exercise: ['AU12_p5', 'AU4_p11']
  datasets: ['PD', 'HEALTHY']
  MDS-UPDRS: ['UPDRS_mimic']

em:
  file: 'em_feature.csv'
  feature_type: [ 'Anger', 'Disgust', 'Fear','Happiness','Sadness','Surprise' ]
  exercise: ['DA', 'DI' ] #'DA',
  datasets: ['PD', 'HEALTHY']
  MDS-UPDRS: ['UPDRS_mimic']

tremor:
  file: 'tremor_feature.csv'
  feature_type: [ 'Fmean', 'Amean', 'Fmax', 'Amax'] #, 'PWmean', 'PWmax' ]
  exercise: [ 'FORE_TIP', 'LITTLE_TIP', 'MIDDLE_TIP', 'RING_TIP', 'THUMB_TIP' ]
  frequency: [ [ 3,6 ], [ 4,9 ], [ 3,12 ] ]
  datasets: ['PD', 'STUDENT']
  MDS-UPDRS: ['3.15_Постуральный тремор', '3.16_Кинетический тремор', '3.17_Амплитуда термора покоя',]

blinking:
  file: 'blinking_feature.csv'
  feature_type: [ 'Frq', 'Num', 'Length'] #, 'Amp'
  exercise: [ 'AU45']
  datasets: ['PD', 'HEALTHY']
  MDS-UPDRS: ['UPDRS_mimic']




PD:
  #number: [71, 72, 75, 90, 62, 81, 83, 52, 98, 100, 11, 34, 39, 40, 43, 45, 49, 54, 70, 91, 53, 99, 3,  4,  5,  6,  9, 12, 13, 14, 20, 21, 22, 1, 17, 19, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 41, 44, 46,]
  #number: [71, 72, 75, 90, 81, 83, 52, 98, 63, 64, 68, 100, 11,34, 39, 40, 43, 45, 49, 70, 91, 53, 99, 2, 7, 8, 15, 16, 18,3,  4,  5,  6,  9, 12, 13, 14, 20, 21, 22, 1, 17, 19, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 37, 38, 41, 44, 46,47,  55,  57, 58, 69, 73, 74, 76, 77, 78, 79, 80, 92, 93, 94, 95, 96, 97,  102]
  number: [1, 2,  3,  4,  5,  6,  7,  8,  9,
           11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
           21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
           31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
           41, 42, 43, 44, 45, 46, 47, 49,
           52, 53, 54, 55, 56, 57, 58, 59, 60,
           61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
           71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
           81, 83, 90,
           #82, 85, 86, 87 - нет lmt
           91, 92, 93, 94, 95, 96, 97, 98, 99,
           100, 102, 103, 104, 105, 106]
  id_name: 'Patient'


HEALTHY:
  number: [1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18]
  id_name: 'Healthy'


STUDENT:
  number:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11, 12 ,13, 14, 15, 16]
  id_name: 'student'


